### ISSUE TITLE
Leader team review

### ISSUE THREAD

**Issue by sommanita** [codeforgso/hackathon#67]
- what did we do well?
- what did we forget to do?
- what should we do again?
- what should we not ever do again?
- what new ideas does everyone have?

**Comment by codylandry** [comment]
I know my kids are still too young to participate, but my wife noticed that it wasn't all that clear before the hackathon what ages were appropriate for the planned projects.  Other than that, we thought everything was awesome.

**Comment by sommanita** [comment]
- what did we do well?  
  food, getting people to compete, messaging (hackathon - conference)  
- what did we forget to do?  
  more swag, solid arrangements for food donations, have tons of extra adapters, music, lanyards, winner things, more time/space for art direction, contingency plans for speaker/facilitators/judges, backup plans for Internet (sponsors), get more people into the talks, justification letter, post-competition team organization
- add:  
  volunteers: facilitators in talks (ask questions, help setup/breakdown, photos/videos), front desk, food, social media, photos, shift, focus on 'convention', more brigade & CfA support, more private space for hackers - or at least a very large area to divide between the groups, storytelling about teams, paid workshops    
- lightning talks:  
  moderated discussion on topic(s): technology & government/ open source & government,  
  for "lightning talks" - at registration/check-in announce that reg is open for lightning talks on day/time,     

track n' hack  

venue:  
performing arts center, new nursing school, GSO Science Center, National Park (Country Park/Battleground), lincoln theater, GSO Historical Museum, Blandwood Mansion,  

NDoCH:  
timco w/aerospace data
