### ISSUE TITLE
Thank you letter to sponsors

### ISSUE THREAD

**Issue by sommanita** [codeforgso/hackathon#70]
- include data from event
- talk about the groups represented 
- how did we spend the money
- next steps

**Comment by nickmjones** [comment]
Dear Civicon15 sponsor,

I wanted to send you this note to let you know how we put your support to good use this weekend at Civicon15.

We had an awesome turnout at HQ Greensboro for our kickoff event, where Jane Nickles broke the news that Greensboro had attained the coveted Digital Cities award for 2015—and declared that Greensboro’s open data portal was open for use by the world. Your generous support bought dinner and drinks for 90+ attendees and VIP guests, and, in the case of HQ Greensboro, gave us a beautiful venue to gather in.

We moved over to the Joint School of Nanoscience and Nanoengineering (JSNN) for our hackathon and conference, and were again joined by almost 100 people and 9 developer teams. Your support fed them (four huge, yummy meals), kept them caffeinated, and filled their swag bags with some really cool stuff. It also helped us to promote the event within the community, and provide an amazing space for our Saturday and Sunday events.

And finally, your support enabled us to award cash prizes to our winning teams. Our first place team built an app that enables potential Greensboro transplants to learn about local ordinance violations in the areas in which they may be relocating. Cody Landry, Sophia Thatch, and Leonard Lawson plan to add more layers of data to their app at Code for Greensboro hack nights. 

We know you could have chosen nearly any event to support. This was a really busy weekend for events like ours, but you made the right choice in supporting us. Here’s why.

Greensboro is turning a corner in terms of its economy, the industries it hosts and helps to advance, and the people it attracts and retains. Other events held this weekend emphasized the “free market” side of the solution: creating startups, obtaining venture capital, and chasing the unicorn of once in a lifetime success. Then you have nonprofits and community organizations, which have always been a big part of our economy. But like any city, Greensboro also relies on attracting and retaining large for profit companies to act as employers. We feel these aims aren’t in total opposition to each other.

Civic entrepreneurship is a "third path" for cities committed to economic development; our teams have built open source projects that help the community, but could easily apply nonprofit and service-based business models to those projects to make them profitable and scalable. In other words, they have the potential to help a whole community—and not just the handful of entrepreneurs in the center.

Your support is a vote for more ideas about how this area--and really our state--can dream bigger about economic development, community organization, and problem solving. We could not do this without you. We're already planning for 2016, so you can count on us keeping you posted. 

With thanks,

Nick Jones
Co-Captain, Code for Greensboro

**Comment by sommanita** [comment]
The only thing I'd add is mention of the communities represented at the event: local schools (UNCG, A&T, Elon), City employees, 32% women, etc. I think including a quick mention of this helps them understand how far we spread their names & dollars - in terms of people not just stuff.
