### ISSUE TITLE
Attendee Poll

### ISSUE THREAD

**Issue by sommanita** [codeforgso/hackathon#76]
- What did we do right?  
  Food, Venues, Speakers, Organizers & Staff, 
- What did we do wrong?
- What did we not do that you wished we would have?
- What should we do again?
- Did you like the food?
- Did you like the venues?
- Did you like the talks?
- Who would like to have speak at the event next year?
- What topics did we miss with our conference sessions?

**Comment by sommanita** [comment]
Do we need these to be drop-downs with choices or text boxes?

**Comment by nickmjones** [comment]
**I enjoyed the speakers, and felt like the subject material presented related to me**
Strongly Disagree 
Disagree
Neither agree nor disagree 
Agree
Strongly Agree
Not sure/not applicable

**I had a good understanding of the schedule of events, and knew where to go**
Strongly Disagree 
Disagree
Neither agree nor disagree 
Agree
Strongly Agree
Not sure/not applicable

**Did you compete in the hackathon this year?**
- [ ] Yes
- [ ] No

**I felt like I understood the hackathon competition and what was expected from a team**
Strongly Disagree 
Disagree
Neither agree nor disagree 
Agree
Strongly Agree
Not sure/not applicable

**I had plenty to eat and drink during the event**
Strongly Disagree 
Disagree
Neither agree nor disagree 
Agree
Strongly Agree
Not sure/not applicable

**I liked the quality of the food options presented**
Strongly Disagree 
Disagree
Neither agree nor disagree 
Agree
Strongly Agree
Not sure/not applicable

**I will attend Civicon 2016**
Strongly Disagree 
Disagree
Neutral
Agree
Strongly Agree

**Is there a speaker you think would make next year’s conference even better?**
[Text box]

**Are there any topics that are specifically important to you?**
- [ ] Technical talks (programming languages, techniques, frameworks, etc.)
- [ ] Professional development (interviewing and hiring, workplace issues, etc.)
- [ ] Civic hacking (technology in cities, Code for America projects, etc.)
- [ ] Design, User Experience and User Interface
- [ ] How cities work, nonprofit issues
- [ ] Community/civic engagement (working in teams, getting project buy-in, etc.)

**Is there anything we should do again?**
[Text box]

**Is there anything we should _not_ do again?**
[Text box]

**If you'd like, please tell us a little about yourself**
I am a...

**Give us any other thoughts you might have.**
[Text box]
