### ISSUE TITLE
Create Presentation Info for Jane

### ISSUE THREAD

**Issue by marshallj** [codeforgso/hackathon#77]
Jane wants to present at the next department head meeting on the applications created at the hackathon and the benefits of providing open data to the community beyond just helping with public information requests. Create some screenshots of the Civicon applications, and maybe prop a couple of the applications up on heroku for her to demo. Need this relatively soon. Meeting is likely the week of Nov. 23rd.

**Comment by marshallj** [comment]
- [x] Violations Near You
- [x] Helping Hands
- [x] GSO Flame
- [x] DIW Greensboro
- [x] False Fire Alarms
- [x] GSO Roulette
- [x] This is Greensboro

**Comment by nickmjones** [comment]
-[ ] One more thing
