### ISSUE TITLE
Thank you letter to speakers

### ISSUE THREAD

**Issue by marshallj** [codeforgso/hackathon#78]
Send email to Civicon15 Speakers

**Comment by marshallj** [comment]
Dear Civicon15 Speaker,

I wanted to take a moment to thank you for speaking this weekend at Civicon15, and to recap some of the great things that happened at the event.

We had an awesome turnout at HQ Greensboro for our kickoff event, where Jane Nickles broke the news that Greensboro had attained the coveted Digital Cities award for 2015—and declared that Greensboro’s open data portal was open for use by the world. 

We moved over to the Joint School of Nanoscience and Nanoengineering (JSNN) for our hackathon and conference, and were again joined by almost 100 people and 9 developer teams. 

The hackathon competition was a great success, with 9 teams participating. Our first place team built an app that enables potential Greensboro transplants to learn about local ordinance violations in the areas in which they may be relocating. Cody Landry, Sophia Thach, and Leonard Lawson plan to add more layers of data to their app at Code for Greensboro hack nights. 

We know you could have chosen to spend your time on many other things this weekend, but you made the right choice in participating with us at Civicon15. The content you allowed us to offer at the event was a huge reason that it was successful. We could not do this without you. We're already planning for 2016, so you can count on us keeping you posted. 

Sincerely,

**Comment by sommanita** [comment]
Sophia Thach
